# Generated by Django 4.1.5 on 2023-01-31 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Wideonyň ady')),
                ('video', models.FileField(upload_to='video', verbose_name='Wideo webinar')),
            ],
            options={
                'verbose_name': 'Wideo',
                'verbose_name_plural': 'Wideo',
            },
        ),
        migrations.CreateModel(
            name='ControlVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doly_wagty', models.CharField(max_length=200)),
                ('gorulen_aralayk', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ulanyjy', to=settings.AUTH_USER_MODEL)),
                ('video_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wideo', to='apps.videoedit')),
            ],
            options={
                'verbose_name': 'Wideony görenler',
                'verbose_name_plural': 'Wideony görenler',
            },
        ),
    ]
