# Generated by Django 4.1.5 on 2023-01-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_videoedit_controlvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoedit',
            name='img',
            field=models.ImageField(default=1, upload_to='media/', verbose_name='Surat'),
            preserve_default=False,
        ),
    ]
